apiVersion: v1
kind: Service
metadata:
    name: results-service
    labels:
        name: results-service
        app: demo-voting-app
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
    selector:
        name: results-app-pod
        app: demo-voting-app